[package]
name = "RustOS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
